{{- if .Values.scyllaManager.enabled }}
apiVersion: v1
kind: Endpoints
metadata:
 name: scylla-manager
 namespace: monitoring
 labels:
  app.kubernetes.io/name: scylla-manager
  helm.sh/chart: {{ include "prometheus-scylladb.chart" . }}
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
subsets:
  - addresses:
{{ toYaml .Values.scyllaManager.endpoints.subsets.addresses | indent 6 }}
    ports:
    - name: metrics
      port: 56090
      protocol: TCP
{{- end }}      
