apiVersion: v1
kind: Service
metadata:
  name: scylla-manager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: scylla-manager
    helm.sh/chart: {{ include "prometheus-scylladb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    cluster: {{ .Values.scylla.cluster }}
    dc: {{ .Values.scylla.dc }}        
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9180
      protocol: TCP
      targetPort: metrics
