apiVersion: v1
kind: Service
metadata:
  name: scylla-manager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: scylla-manager
    helm.sh/chart: {{ include "prometheus-scylladb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 56090
      protocol: TCP
      targetPort: metrics
