apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-scylladb.fullname" . }}
  namespace: monitoring
  labels:
    app.kubernetes.io/name: {{ include "prometheus-scylladb.name" . }}
    helm.sh/chart: {{ include "prometheus-scylladb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: prometheus-operator
spec:
  endpoints:
  - port: node-metrics
    interval: 15s
    honorLabels: true
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_label_cluster]
      targetLabel: cluster    
    - sourceLabels: [__meta_kubernetes_service_label_dc]
      targetLabel: dc    
  - port: metrics
    interval: 15s
    honorLabels: true
    scheme: http    
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_label_cluster]
      targetLabel: cluster    
    - sourceLabels: [__meta_kubernetes_service_label_dc]
      targetLabel: dc
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-scylladb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - monitoring
