{{- $secretMountPath := "/etc/gcloud/service-account.json" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipeline.fullname" . }}
  labels:
{{ include "pipeline.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pipeline.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pipeline.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: "pipelines-permissions-service-account"
        secret:
          secretName: pipelines-permissions-service-account
      containers:
        - name: {{ include "pipeline.name" . }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: "pipelines-permissions-service-account"
              readOnly: true
              mountPath: {{ $secretMountPath }}
              subPath: service-account.json
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: {{ $secretMountPath }}
            - name: PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: augury-common-services
                  key: GOOGLE_PROJECT_ID
          envFrom:
          - configMapRef:
              name: {{ include "pipeline.name" . }}
          - configMapRef:
              name: augury-common-services
          - configMapRef:
              name: augury-common-scylla
          - secretRef:
              name: augury-common-scylla
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
