# Default values for pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride:

image:
  repository: us.gcr.io/production-02cb28ec
  name:
  tag:
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

tolerations:
  - key: cloud.google.com/gke-preemptible
    operator: Equal
    value: "true"
    effect: NoSchedule
nodeSelector:
  cloud.google.com/gke-preemptible: "true"


affinity: {}

envVars:
  inputPubsubSub: temp
  outputPubsubTopic: temp
