scylla:
  endpoints:
    subsets:
      addresses:
      - ip: 10.118.0.2
      - ip: 10.118.0.3
      - ip: 10.118.0.4
scylla-manager:
  endpoints:
    subsets:
      addresses:
      - ip: 10.118.0.107     
