apiVersion: v1
kind: Service
metadata:
  name: {{ include "scylladb-prometheus.fullname" . }}
  namespace: monitoring
  labels:
    app.kubernetes.io/name: {{ include "scylladb-prometheus.name" . }}
    helm.sh/chart: {{ include "scylladb-prometheus.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: metrics
