apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "scylladb-prometheus.fullname" . }}
  namespace: monitoring
  labels:
    app.kubernetes.io/name: {{ include "scylladb-prometheus.name" . }}
    helm.sh/chart: {{ include "scylladb-prometheus.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    prometheus: kube-prometheus
spec:
  endpoints:
  - port: node-metrics
    interval: 15s
    honorLabels: true
    scheme: http
  - port: metrics
    interval: 15s
    honorLabels: true
    scheme: http    
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scylladb-prometheus.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - monitoring
