apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nsqadmin"
  labels:
    app: "nsqadmin"
    chart: {{ template "nsqd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: "nsqadmin"
      release: {{ .Release.Name }}
  replicas: {{ .Values.nsqadminReplicaCount }}
  template:
    metadata:
      labels:
        app: "nsqadmin"
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: "nsqadmin"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/nsqadmin"]
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        args:
        {{- range $i, $e := until (int .Values.nsqlookupdReplicaCount) }}
        - --lookupd-http-address=nsqlookupd-{{ $i }}.nsqlookupd.$(NAMESPACE).svc.cluster.local:4161
        {{- end}}
        ports:
        - name: http
          containerPort: 4171
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 12 }}
