apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nsqadmin.name }}
  labels:
    app: {{ .Values.nsqadmin.name }}
    chart: {{ template "nsqd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http 
    protocol: TCP
    port: 80
    targetPort: 4171
  selector:
    app: {{ .Values.nsqadmin.name }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
