apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nsqd.name }}
  labels:
    app: nsqd
    chart: {{ template "nsqd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: main
    protocol: TCP
    port: 4150
    targetPort: 4150
  - name: secondary
    protocol: TCP
    port: 4151
    targetPort: 4151
  - name: metrics
    protocol: TCP
    port: 9117
    targetPort: 9117    
  selector:
    app: {{ .Values.nsqd.name }}
    release: {{ .Release.Name }}
  clusterIP: None
