apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nsqd
  labels:
    app: nsqd
    chart: {{ template "nsqd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: nsqd
  selector:
    matchLabels:
      app: nsqd
      release: {{ .Release.Name }}
  replicas: {{ .Values.nsqdReplicaCount }}
  template:
    metadata:
      labels:
        app: nsqd
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nsq-exporter
        image: emaincourt/nsq_exporter:1.1.0
        imagePullPolicy: Always
        command: ["sh", "-c"]
        args:
        - /nsq_exporter -nsqd.addr=http://$HOSTNAME.nsqd.{{ .Release.Namespace }}.svc.cluster.local:4151/stats
        ports:
        - containerPort: 9117
          hostPort: 9117
      - name: nsqd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c"]
        env:
        - name: NAMEPSPACE
          value: {{ .Release.Namespace }}
        args:
        - |
          /nsqd -broadcast-address=$HOSTNAME.nsqd.${NAMEPSACE}.svc.cluster.local \
          --max-req-timeout=3h0m0s \
          --max-msg-timeout=1h0m0s \
          {{- range $i, $e := until (int .Values.nsqlookupdReplicaCount) }}
          --lookupd-tcp-address=nsqlookupd-{{ $i }}.nsqlookupd.${NAMEPSACE}.svc.cluster.local:4160 \
          {{- end}}
          --data-path=/data \
          --mem-queue-size=0
        ports:
        - containerPort: 4150
          hostPort: 4150
        - containerPort: 4151
          hostPort: 4151
        livenessProbe:
          httpGet:
            path: /ping
            port: 4151
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /ping
            port: 4151
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "{{ .Values.dataVolumeClaim.storageClassName }}"
      resources:
        requests:
          storage: "{{ .Values.dataVolumeClaim.storage }}"
