apiVersion: v1
kind: Service
metadata:
  name: {{ template "nsqd.fullname" . }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"    
  labels:
    app: {{ template "nsqd.name" . }}
    chart: {{ template "nsqd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: main
    protocol: TCP
    port: 4150
    targetPort: 4150
  - name: secondary
    protocol: TCP
    port: 4151
    targetPort: 4151
  selector:
    app: nsqd
  type: {{ .Values.service.type }}
