apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nsqlookupd.name }}
  labels:
    app: {{ .Values.nsqlookupd.name }}
    chart: {{ template "nsqd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: main
    protocol: TCP
    port: 4160
    targetPort: 4160
  - name: secondary
    protocol: TCP
    port: 4161
    targetPort: 4161
  selector:
    app: {{ .Values.nsqlookupd.name }}
    release: {{ .Release.Name }}
  clusterIP: None 
