apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nsqlookupd
  labels:
    app: nsqlookupd
    chart: {{ template "nsqd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: nsqlookupd
  selector:
    matchLabels:
      app: nsqlookupd
      release: {{ .Release.Name }}
  replicas: {{ .Values.nsqlookupdReplicaCount }}
  template:
    metadata:
      labels:
        app: nsqlookupd
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nsqlookupd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c"]
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        args:
        - /nsqlookupd --broadcast-address=$HOSTNAME.nsqlookupd.$(NAMESPACE).svc.cluster.local
        ports:
        - containerPort: 4160
          hostPort: 4160
        - containerPort: 4161
          hostPort: 4161
        resources:
{{ toYaml .Values.resources | indent 12 }}
