{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.alerting.rules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  name: nsqd
  namespace: monitoring
  labels:
    app.kubernetes.io/name: {{ include "nsqd.name" . }}
    helm.sh/chart: {{ include "nsqd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: prometheus-operator
spec:
  groups:
{{ toYaml .Values.serviceMonitor.alerting.rules | indent 4 }}
{{- end }}
