{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.nsqd.name }}
  namespace: monitoring
  labels:
    app.kubernetes.io/name: {{ include "nsqd.name" . }}
    helm.sh/chart: {{ include "nsqd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: prometheus-operator
spec:
  endpoints:
  - port: metrics
    interval: 15s
    honorLabels: true
    scheme: http
  selector:
    matchLabels:
      app: {{ .Values.nsqd.name }}
      release: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
