image:
  repository: us.gcr.io/production-02cb28ec/fluentd-kubernetes-daemonset
  tag: v1-debian-syslog
  pullPolicy: Always

resources:
  limits:
    memory: 800Mi
  requests:
    cpu: 100m
    memory: 800Mi
