apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ template "fluentd-kubernetes-daemonset.name" . }}
    chart: {{ template "fluentd-kubernetes-daemonset.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    k8s-app: "{{ .Chart.Name }}-logging"
    version: v1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: "EnsureExists"
  namespace: {{ .Release.Namespace }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/fluentconf: {{ include (print $.Template.BasePath "/fluentconf.yaml") . | sha256sum }}
        checksum/fluentkubernetesconf: {{ include (print $.Template.BasePath "/fluentkubernetesconf.yaml") . | sha256sum }}
      labels:
        app: {{ template "fluentd-kubernetes-daemonset.name" . }}
        chart: {{ template "fluentd-kubernetes-daemonset.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: {{ .Chart.Name }}
      serviceAccountName: {{ .Chart.Name }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: FLUENT_ELASTICSEARCH_USER
          value: none
        - name: FLUENT_ELASTICSEARCH_PASSWORD
          value: none
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: fluentkubernetesconfig
          mountPath: /fluentd/etc/kubernetes.conf
          subPath: kubernetes.conf
        - name: fluentconfig
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
      - name: fluentkubernetesconfig
        configMap:
          name: fluentkubernetesconf
      - name: fluentconfig
        configMap:
          name: fluentconf
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
